#!/bin/python
#The KY040 Pinout is as follows: 
# CLK is Encoder Pin A, DT is Encoder Pin B, and GND is Encoder Pin C.
import gpiozero
from RPi import GPIO
from time import sleep

led = gpiozero.LED(21)
button = gpiozero.Button(20)

clk = 15
dt = 14

GPIO.setmode(GPIO.BCM)
GPIO.setup(clk,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)
GPIO.setup(dt,GPIO.IN,pull_up_down=GPIO.PUD_DOWN)



def pressed():
	print("Button has been pressed")
	led.on()

def released():
	print("Button has been released")
	led.off()


counter = 0
clkLastState = GPIO.input(clk)

while True:
	text = ""
	button.when_pressed = pressed
	button.when_released = released

	clkState = GPIO.input(clk)
	dtState = GPIO.input(dt)
	if clkState != clkLastState:
		if dtState != clkState:
			text = "Counterclockwise Turn"
                        counter -= 0.5
		else:
			text = "Clockwise Turn"
                        counter += 0.5

		if counter % 1 == 0:
			print text
			print counter
		if (counter == 20) or (counter == -20):
			counter = 0
		clkLastState = clkState
		sleep(0.02)
